---
- name: Restore Apache httpd
  hosts: rhel01-nostromo.demoredhat.com
  become: true
  tasks:
    - name: Remove InvalidDirectiveHere
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^InvalidDirectiveHere$'
        state: absent

    - name: Restart apache
      service:
        name: httpd
        state: restarted

    - name: Get httpd status
      command: systemctl status httpd
      register: httpd_status
      changed_when: false

    - name: Show httpd status
      debug:
        var: httpd_status.stdout_lines
