- name: Send API request and debug complete response
  hosts: localhost
  gather_facts: false
  vars:
    api_prompt: "\n\n### Instructions:\nWe have an issue on our RHEL Linux server.  Here is the output: Nov 06 10:29:36 rhel01-nostromo.demoredhat.com systemd[1]: Starting The Apache HTTP Server...\nNov 06 10:29:36 rhel01-nostromo.demoredhat.com httpd[8787]: Server configured, listening on: port 80\nNov 06 10:29:36 rhel01-nostromo.demoredhat.com systemd[1]: Started The Apache HTTP Server.\nNov 06 10:33:03 rhel01-nostromo.demoredhat.com systemd[1]: Stopping The Apache HTTP Server...\nNov 06 10:33:04 rhel01-nostromo.demoredhat.com systemd[1]: httpd.service: Deactivated successfully.\nNov 06 10:33:04 rhel01-nostromo.demoredhat.com systemd[1]: Stopped The Apache HTTP Server.\nNov 06 10:33:04 rhel01-nostromo.demoredhat.com systemd[1]: Starting The Apache HTTP Server...\nNov 06 10:33:04 rhel01-nostromo.demoredhat.com httpd[10097]: AH00526: Syntax error on line 35 of /etc/httpd/conf/httpd.conf:\nNov 06 10:33:04 rhel01-nostromo.demoredhat.com httpd[10097]: Invalid command 'InvalidDirectiveHere', perhaps misspelled or defined by a module not included in the server configuration\nNov 06 10:33:04 rhel01-nostromo.demoredhat.com systemd[1]: httpd.service: Main process exited, code=exited, status=1/FAILURE\n\n### Response:\n"
  tasks:

    - name: Send POST request using uri module
      ansible.builtin.uri:
        url: "http://{{ redhat_ai_server | default('98.80.168.118') }}:8000/v1/completions"
        method: POST
        headers:
          accept: "application/json"
          Content-Type: "application/json"
          Authorization: "Bearer {{ api_token | default('ansible123!') }}"
        body:
          prompt: "{{ api_prompt }}"
          max_tokens: "{{ max_tokens | default('2000') }}"
        body_format: json
        return_content: true
        status_code: 200
        timeout: 60
      register: response

    - name: Debug response
      ansible.builtin.debug:
        var: response
