---
- name: Stop model serve running in the background
  hosts: instructlab-g6
  gather_facts: false
  tasks:
    - name: Check if InstructLab is already running
      block:
        - name: Check if something is listening on port 8000 for TCP
          ansible.builtin.wait_for:
            host: 0.0.0.0
            port: 8000
            state: absent
            timeout: 5
          register: port_check
      rescue:
        - name: Check for ilab process
          ansible.builtin.shell: "pgrep -f 'ilab model serve'"
          register: ilab_pid
          ignore_errors: true

        - name: Kill ilab process
          ansible.builtin.shell: "kill -9 {{ ilab_pid.stdout }}"
          when: ilab_pid.stdout is defined and ilab_pid.stdout != ""
          ignore_errors: true
          register: kill_result

        - name: Display result
          ansible.builtin.debug:
            msg: "Process 'ilab model serve' {{ 'was killed' if kill_result is succeeded else 'not found or could not be killed' }}"

        - name: Check if something is listening on port 8000 for TCP
          ansible.builtin.wait_for:
            host: 0.0.0.0
            port: 8000
            state: absent
            timeout: 5
          register: port_check

        - name: Confirm that model serve stopped successfully
          ansible.builtin.debug:
            msg: "ilab model serve stopped successfully, nothing is listening on port 8000"
          when: port_check is succeeded
