---
- name: Send API request and debug complete response
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Send POST request using uri module
      ansible.builtin.uri:
        url: "http://98.80.168.118:8000/v1/completions"
        method: POST
        headers:
          accept: "application/json"
          Content-Type: "application/json"
        body: >
          {
            "prompt": "\n\n### Instructions:\nWhat is the capital of USA?\n\n### Response:\n",
            "stop": [
              "\n",
              "###"
            ]
          }
        body_format: json
        return_content: yes
        status_code: 200
        timeout: 60
      register: response

    - name: Check if response is JSON and debug output
      ansible.builtin.debug:
        msg: "{{ response.json if response.json is defined else response.content }}"
